services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanban_board_dev
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - gem_cache:/usr/local/bundle
    depends_on:
      - db
    command: bash -c "bundle install && rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
    command: bash -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"

volumes:
  gem_cache:
  node_modules: